### ISSUE TITLE
Babo

### ISSUE THREAD

**Issue by hyriph** [iseol/BOJ-Source-Code#1]
You didn't solve all problem in BOJ
It's big problem

**Comment by hyriph** [comment]
I can't, but you must do it

**Comment by iseol** [comment]
anyone cant solve all problem in BOJ YEE BBAK DAE GARI YA

**Comment by hyriph** [comment]
GAE SSAE GGI YA

**Comment by iseol** [comment]
no dap issue so close

**Comment by STR-HK** [comment]
Are you ok?

**Comment by STR-HK** [comment]
You don't seem well
